[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false

[theme]
primaryColor = "#4ECDC4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
